export const AUTH_LOGIN_PENDING = 'AUTH_LOGIN_PENDING';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILD = 'AUTH_LOGIN_FAILD';
export const AUTH_LOGIN_ERROR = 'AUTH_LOGIN_ERROR';
