// LOGIN
export const AUTH_SIGNIN = 'AUTH_SIGNIN';
export const AUTH_SIGNIN_SUCCESS = 'AUTH_SIGNIN_SUCCESS';
export const AUTH_SIGNIN_FAILED = 'AUTH_SIGNIN_FAILED';
export const AUTH_AUTO_SIGNIN = 'AUTH_AUTO_SIGNIN';
export const AUTH_SIGNOUT = 'AUTH_SIGNOUT';
export const AUTH_SIGNOUT_SUCCESS = 'AUTH_SIGNOUT_SUCCESS';
export const AUTH_REGISTER = 'AUTH_REGISTER ';
export const AUTH_REGISTER_SUCCESS = 'AUTH_REGISTER ';
export const AUTH_REGISTER_FAILD = 'AUTH_REGISTER_FAILD ';
export const AUTH_ADD_ADDRESS = 'AUTH_ADD_ADDRESS ';
export const AUTH_ADD_ADDRESS_SUCCESS = 'AUTH_ADD_ADDRESS_SUCCESS ';
export const AUTH_GET_ADDRESS_SUCCESS = 'AUTH_GET_ADDRESS_SUCCESS ';
export const AUTH_CLEAR_ADDRESS = 'AUTH_CLEAR_ADDRESS ';
export const AUTH_EDIT_ADDRESS = 'AUTH_EDIT_ADDRESS';
export const AUTH_UPDATE_ADDRESS = 'AUTH_UPDATE_ADDRESS';
export const AUTH_NUMBER_NOTIFICATION = 'AUTH_NUMBER_NOTIFICATION';
export const AUTH_UPDATE_NUMBER_BADGES = 'AUTH_UPDATE_NUMBER_BADGES';

export const AUTH_CLEAR_NOTIFICATION = 'AUTH_CLEAR_NOTIFICATION';
export const AUTH_DELETE_ADDRESS = 'AUTH_DELETE_ADDRESS';
export const AUTH_GET_NOTIFICATIONS_SUCCESS = 'AUTH_GET_NOTIFICATIONS_SUCCESS';
export const AUTH_DELETE_NOTIFICATIONS = 'AUTH_DELETE_NOTIFICATIONS';
export const AUTH_UPDATE_PROFILE = 'AUTH_UPDATE_PROFILE';
export const AUTH_UPDATE_SUCCESS_PROFILE = 'AUTH_UPDATE_SUCCESS_PROFILE';
